### PR TITLE
update Immich to v1.90.2

### PR DESCRIPTION
**Pull request by gschurck**
⚠️ Next version will have breaking changes in docker-compose (v1.91).

### CODE REVIEW

**Comment by dragonfire1119** [comment]
> ⚠️ Next version will have breaking changes in docker-compose (v1.91).

Great, it's good to have that information. Are you interested in tackling the breaking changes, or should I take care of them?

Additionally, could you please share your insights in the following thread with Immich? They are seeking information on this topic: https://community.bigbeartechworld.com/t/any-thoughts-on-how-good-is-immich/374?u=dragonfire1119

Thank you for your assistance!

**Comment by dragonfire1119** [comment]
Published at: https://community.bigbeartechworld.com/t/update-immich-to-v1-90-2-on-bigbearcasaos/375?u=dragonfire1119

Thank you!

**Comment by gschurck** [comment]
> > ⚠️ Next version will have breaking changes in docker-compose (v1.91).
> 
> Great, it's good to have that information. Are you interested in tackling the breaking changes, or should I take care of them?

Yep I am, but I am wondering about this part :
image
By default the user created from docker-compose env variables with CasaOS should be a postgres superuser in the postgres Docker image right ?

> Additionally, could you please share your insights in the following thread with Immich? They are seeking information on this topic: https://community.bigbeartechworld.com/t/any-thoughts-on-how-good-is-immich/374?u=dragonfire1119
> 
> Thank you for your assistance!

yes no problem

**Comment by dragonfire1119** [comment]
> > > ⚠️ Next version will have breaking changes in docker-compose (v1.91).
> > 
> > 
> > Great, it's good to have that information. Are you interested in tackling the breaking changes, or should I take care of them?
> 
> Yep I am, but I am wondering about this part : image By default the user created from docker-compose env variables with CasaOS should be a postgres superuser in the postgres Docker image right ?
> 
> > Additionally, could you please share your insights in the following thread with Immich? They are seeking information on this topic: https://community.bigbeartechworld.com/t/any-thoughts-on-how-good-is-immich/374?u=dragonfire1119
> > Thank you for your assistance!
> 
> yes no problem

I'm considering informing the user about running a Bash script. 

You can find the initial version of the Bash script at the following link: https://github.com/bigbeartechworld/big-bear-scripts/tree/master/immich-add-vector-to-db. 

Please don't hesitate to make any modifications if you believe they are necessary.

**Pull request merged**
