### PR TITLE
update Immich to v1.86.0

### PR DESCRIPTION
**Pull request by gschurck**

### CODE REVIEW

**Comment by robotron2084** [comment]
I was just about to make this PR! Thank you!

**Comment by dragonfire1119** [comment]
Prior to merging and expressing my gratitude for your update, I would like to inquire whether this has been tested, or if further testing is required on my part?

**Comment by dragonfire1119** [comment]
Posted the update here: https://community.bigbeartechworld.com/t/update-immich-to-v1-86-0-on-bigbearcasaos/264

**Comment by gschurck** [comment]
Thanks !

**Pull request merged**
